services:
    php-cli:
        image: php:8.4-cli
        container_name: php-cli
        command: php /app/demo/bin/test3.php
        volumes:
            - .:/app
        depends_on:
            - loki
            - prometheus
    loki:
        image: grafana/loki:3.4.6
        container_name: loki
        ports:
            - 3100:3100
    grafana:
        image: grafana/grafana:12.4.0-20977568970-ubuntu
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - ./demo/etc/grafana/provisioning:/etc/grafana/provisioning
        depends_on:
            - loki
            - prometheus
        environment:
            - GF_SECURITY_ADMIN_USER=user346246
            - GF_SECURITY_ADMIN_PASSWORD=user346246
    prometheus:
        image: prom/prometheus:v3.0.0-beta.0
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./demo/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml