binance_trade:
    api_key: '%env(BINANCE_API_KEY)%'
    signer:
        class: 'Empiriq\BinanceTradeBundle\Common\Signers\HmacSigner'
        arguments: ['%env(BINANCE_API_SECRET)%']
#        class: 'Empiriq\BinanceTradeBundle\Common\Signers\Ed25519Signer'
#        arguments: ['%env(EMPIRIQ_BINANCE_CONNECTOR_WEBSOCKET_SIGNER_PRIVATE_KEY_PATH)%']
    transports:
        futures_usd:
            rest_api_uri: 'https://testnet.binancefuture.com'
            websocket_api_uri: 'wss://testnet.binancefuture.com/ws-fapi/v1'
            websocket_market_streams_uri: 'wss://fstream.binancefuture.com/ws'
            streams:
                trade: [['BTCUSDT']]
