# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    monolog.default_level: debug
    binance_trade.default_environment: mainnet
    binance_trade.default_auth: unsigned

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    _instanceof:
        Empiriq\Contracts\RunnableInterface:
            tags: [ 'empiriq.runnable' ]
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true
    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'
    Psr\Container\ContainerInterface: '@service_container'
    Psr\Log\LoggerInterface: '@logger'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Prometheus\Storage\InMemory: ~
    Prometheus\CollectorRegistry:
        arguments:
            $storageAdapter: '@Prometheus\Storage\InMemory'
    PrometheusPushGateway\PushGateway:
        arguments:
            $address: 'http://pushgateway:9091'
    Empiriq\Contracts\Runner:
        public: true
        arguments:
            $runners: !tagged_iterator empiriq.runnable
    Empiriq\Logging\RecordMessagePrefixPredicate:
        arguments:
            $prefix: 'Received response (id:'
    Empiriq\Logging\RecordRoutingHandler:
        arguments:
            $routes:
                - when: '@Empiriq\Logging\RecordMessagePrefixPredicate'
                  handler: '@monolog.handler.binance_api_file'
            $fallback: ~
    App\:
        resource: '../src/'
