monolog:
    handlers:
        stdout:
            type: stream
            path: php://stdout
            level: '%env(default:monolog.default_level:MONOLOG_LEVEL)%'
            formatter: monolog.formatter.json
